version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payara-web
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data

  client:
    build:
      context: ./client
    container_name: php-client
    depends_on:
      - web
